### ISSUE TITLE
如果外部存储卡不能用。会出错。

### ISSUE THREAD

**Issue by guobinAndroid** [YancyYe/GalleryPick#20]
```
FATAL EXCEPTION: main
Process: com.yancy.gallerypickdemo, PID: 6500 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.yancy.gallerypickdemo/com.yancy.gallerypick.activity.GalleryPickActivity}: java.lang.IllegalArgumentException: Failed to find configured root that contains /data/data/com.yancy.gallerypickdemo/cache/20170220200606.jpg
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2441)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2501)
 at android.app.ActivityThread.access$1000(ActivityThread.java:153)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1367)
 at android.os.Handler.dispatchMessage(Handler.java:102)
 at android.os.Looper.loop(Looper.java:154)
 at android.app.ActivityThread.main(ActivityThread.java:5462)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
 Caused by: java.lang.IllegalArgumentException: Failed to find configured root that contains /data/data/com.yancy.gallerypickdemo/cache/20170220200606.jpg
 at android.support.v4.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:711)
 at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:400)
 at com.yancy.gallerypick.activity.GalleryPickActivity.showCameraAction(GalleryPickActivity.java:332)
 at com.yancy.gallerypick.activity.GalleryPickActivity.onCreate(GalleryPickActivity.java:99)
 at android.app.Activity.performCreate(Activity.java:6303)
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2394)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2501) 
 at android.app.ActivityThread.access$1000(ActivityThread.java:153) 
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1367) 
 at android.os.Handler.dispatchMessage(Handler.java:102) 
 at android.os.Looper.loop(Looper.java:154) 
 at android.app.ActivityThread.main(ActivityThread.java:5462) 
 at java.lang.reflect.Method.invoke(Native Method) 
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739) 
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629) 
```

log如上。是FileProvider的问题

**Comment by guobinAndroid** [comment]
已解决

**Comment by guobinAndroid** [comment]
已解决，xml 中再加上内部存储就可以了。
